### ISSUE TITLE
访问404

### ISSUE THREAD

**Issue by yuhal** [409915016/filmy#5]
- 执行
```
$ yarn run dev 
```

- 查看 http://localhost:8080
```
Cannot GET /
```

您好，请问这是出于什么原因？

**Comment by 409915016** [comment]
当时的 webpack 构建工具还是 2.x 版本，`devDependencies` 也没有写死依赖包的版本号，导致安装了较新版本的包与目前配置冲突的问题。

```cmd
 ERROR  Failed to compile with 1 errors                                                           0:19:38
 error 


> Listening at http://localhost:8080
```

如果你了解过 [Vue-cli](https://cli.vuejs.org/) 和构建多页面应用相关内容，可以将源代码迁移到新模板中；

如果没有，我会考虑更新项目构建部分的内容，这可能要等上一阵子。

**Comment by yuhal** [comment]
可惜的是我对 Vue-cli 使用不多，还不具备将源代码迁移到新模板中的能力。
感谢有您的帮忙👍，等 filmy 下次更新，我再来尝试搭建。

**Comment by 409915016** [comment]
> 可惜的是我对 Vue-cli 使用不多，还不具备将源代码迁移到新模板中的能力。
> 感谢有您的帮忙👍，等 filmy 下次更新，我再来尝试搭建。

好，谢谢理解。

**Comment by 409915016** [comment]
> 可惜的是我对 Vue-cli 使用不多，还不具备将源代码迁移到新模板中的能力。
> 感谢有您的帮忙👍，等 filmy 下次更新，我再来尝试搭建。

好，谢谢理解。
